"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['FotoPDF.py']
DATA_FILES = ['FotoPDF.png', 'font_default.ttf']
OPTIONS = {
    'packages': ['reportlab', 'PyQt5', 'os', 'json']
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)